/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;
import Entidades.Incidente;
import java.util.List;

/**
 *
 * @author Proyector
 */
public class FrameRegistrar extends javax.swing.JFrame {

private FrameVisualizar padre; 
private Incidente incidente;
 private boolean estoyEditando = false;
 public static List<Incidente> listaDeIncidentes;
  
    /**
     * Creates new form RegistrarIncidente
     */
    public FrameRegistrar() {
        initComponents();
    }
    public FrameRegistrar(FrameVisualizar padre){
      initComponents();
      this.padre = padre;
     
      }

   

                                       
private void salir(){
      padre.setVisible(true);
      this.dispose();
    }


 




 public FrameRegistrar(FrameVisualizar padre, Incidente incidente) {
        initComponents();
        this.padre = padre;
        this.incidente = incidente;
        this.estoyEditando = true;
       // this.Registrar.setVisible(false);
        //this.jLabel9.setVisible(false);
        //lblTitulo.setText("Visualizar Cita");
        this.txtTipo.setText(incidente.getTipo());
        this.txtHora.setText(incidente.getHora());
        this.txtFecha.setText(incidente.getFecha());
        this.txtDescripcion.setText(incidente.getDescripcion());
        
//        cbEspecialidad.removeAllItems();
//        cbEspecialidad.addItem(cita.getEspecialidad().getNombre());
//        
//        cbFecha.removeAllItems();
//        cbFecha.addItem(GestorDeCitas.fechaDisponibles.get(cita.getFecha()));
//        
//        cbHora.removeAllItems();
//        cbHora.addItem(GestorDeCitas.horasDisponibles.get(cita.getHora()));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTipo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        lblRegistrar = new javax.swing.JLabel();
        lblAñadir = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipo.setBorder(null);
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 170, 30));

        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 170, 30));

        txtHora.setBorder(null);
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 170, 30));

        txtDescripcion.setBorder(null);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 270, 250));

        lblRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrarr.png"))); // NOI18N
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, -1));

        lblAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadi.png"))); // NOI18N
        lblAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAñadirMouseClicked(evt);
            }
        });
        jPanel1.add(lblAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RegistrarIncidente.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAñadirMouseClicked
        // TODO add your handling code here:
        FrameRegistroPrueba pantallaRegistro = new FrameRegistroPrueba(this);  
        pantallaRegistro.setLocationRelativeTo(this); 
        pantallaRegistro.setVisible(true);
        
        
        this.setVisible(false);
    }//GEN-LAST:event_lblAñadirMouseClicked

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:}
        salir();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        // TODO add your handling code here:
        
    
      if (incidente != null) {
        // Actualizar el estudiante existente
        incidente.setTipo(txtTipo.getText());
        incidente.setFecha(txtFecha.getText());
        incidente.setHora(txtHora.getText());
        incidente.setDescripcion(txtDescripcion.getText());
        // Llama a un método en FrameEstudiantes para actualizar el modelo del JList.
        this.padre.actualizarEstudiante(incidente);
    } else {
        // Crear un nuevo estudiante
        String tipo = txtTipo.getText();
  String fecha = txtFecha.getText();
   String hora = txtHora.getText();
   String descripcion = txtDescripcion.getText();
        Incidente nuevoIncidente = new Incidente(fecha, tipo, descripcion, hora);
        nuevoIncidente.setTipo(txtTipo.getText()); 
        nuevoIncidente.setFecha(txtFecha.getText());
        nuevoIncidente.setDescripcion(txtDescripcion.getText());
        
        // Llama a un método en FrameEstudiantes para agregar el nuevo estudiante al modelo del JList.
        this.padre.agregarEstudiante(nuevoIncidente);
    }
    
    // Mostrar FrameEstudiantes nuevamente y cerrar FrameEstudiante
    this.padre.setVisible(true);
    this.dispose();
    
    
    
    
    
    }//GEN-LAST:event_lblRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAñadir;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
